title: Runaway Robot
landing: true
steps:
  - title: Start main.js
  - title: Draw the Scene
    completion:
      - engaged
  - title: Make the Robot Run
  - title: Stop the Loop with SPACE
    completion:
      - internal
  - title: Click to Stop Too
    completion:
      - external
